name: Checks

on:
  push:
  pull_request:

jobs:
  build:
    name: >
      test-${{ matrix.os }} -
      py${{ matrix.python-version }} -
      ${{ matrix.extras == '.' && 'base' || 'skimage' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install fftw3 libs (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfftw3-dev libfftw3-double3

      - name: Install fftw3 libs (macOS)
        if: runner.os == 'macOS'
        run: brew install fftw

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --group tests
          python -m pip install coverage flake8
          python -m pip install -e .

      - name: List installed packages
        run: pip freeze

      - name: Test with pytest
        run: coverage run --source=xpunwrap -m pytest tests --ignore=tests/benchmarking

      - name: Lint with flake8
        run: flake8 --exclude _version.py .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
